export type {
  ArrT as Arr,
  ArrEitherT as ArrEither,
  ArrTaskT as ArrTask,
  DictT as Dict,
  DictEntryT as DictEntry,
  EitherT as Either,
  OptionT as Option,
  TaskT as Task,
  Tuple2T as Tuple2,
} from './mod.g';
export {
  Arr as A,
  ArrEither as AE,
  ArrTask as AT,
  Dict as D,
  Either as E,
  Option as O,
  Tuple2 as P2,
  Task as T,
} from './mod.g';
